config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "public#index" 
  get "u/:username" => "public#profile", as: :profile
  resources :communities do
    resources :posts
    
  end
  post "post/vote" => "votes#create"
  resources :subscriptions 
 resources :comments, only: [:create]
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :communities, through: :subscriptions
  has_many :posts
  has_many :votes
  has_many :comments
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates_presence_of :first_name, :last_name, :username

  def full_name
    "#{first_name} #{last_name}"
  end

  def upvoted_post_ids
    self.votes.where(upvote: true).pluck(:post_id)
  end

  def downvoted_post_ids
    self.votes.where(upvote: true).pluck(:post_id)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment <ApplicationRecord
    belongs_to :post
    belongs_to :account

    validates_presence_of :message, :account_id, :post_id
end

app/models/community.rb
class Community < ApplicationRecord

    belongs_to :account
    has_many :posts
    has_many :subscriptions
    has_many :subscribers, through: :subscriptions, source: :account
    validates_presence_of :url, :name, :rules
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :account
    belongs_to :community
    has_many :comments
    has_many :votes
    validates_presence_of :title, :body, :account_id, :community_id

    def score
        if self.upvotes > 0 || self.downvotes > 0
            self.upvotes > 0 ? (self.upvotes - self.downvotes) : (self.downvotes * -1)
        else
            0
        end
    end
end

app/models/subscription.rb
class Subscription < ApplicationRecord
    belongs_to :account
    belongs_to :community
end

app/models/vote.rb
class Vote < ApplicationRecord
    belongs_to :account
    belongs_to :post
    validates_uniqueness_of :account_id, scope: :post_id

    after_create :increment_vote
    after_destroy :decrement_vote
    
    private
    def increment_vote
       
        field = self.upvote ? :upvotes : :downvotes
        Post.find(self.post_id).increment(field).save
    end

    def decrement_vote
        field = self.upvote ? :upvotes : :downvotes
        Post.find(self.post_id).decrement(field).save 
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :username])
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username])

    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    

    def create
        @comment = Comment.new comment_params
       
        @comment.account_id = current_account.id


        respond_to do |format|
            format.js{
                if @comment.save
                    @comments = Comment.where(post_id: @comment.post_id)
                    render "comments/create"
                else
                   redirect_to root_path
                end 
            }
        end
    
    end
    def comment_params
        params.require(:comment).permit(:message, :post_id)
    end
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
    before_action :authenticate_account!, except: [:index, :show ]
    before_action :set_community, only: [:show ]

    def index
        @communities = Community.all
    end

    def new
        @community = Community.new
    end

    def show
        @posts = @community.posts
        @subscriber_count = @community.subscribers.count
        @is_subscribed = account_signed_in? ? Subscription.where(community_id: @community.id, account_id: current_account.id).any? : false
        @Subscription = Subscription.new
    end

    def  create
        @community = Community.new community_values
        @community.account_id = current_account.id
        if @community.save
            redirect_to communities_path
        else
            render :new
        end

    end

    private
    def set_community
        @community = Community.find(params[:id])

    end

    def community_values
        params.require(:community).permit(:name, :url, :summary, :rules)
    end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    
        before_action :authenticate_account!, except: [:index, :show]
        before_action :set_post, only: [:show ]
        before_action :auth_subscriber, only: [:new ]

    
        def index
            @posts = Post.all
        end
    
        def new
            @community = Community.find(params[:community_id])
            @post = Post.new
        end
    
        def show
            @comment = Comment.new

        end
    
        def  create
            @post = Post.new post_values
            @post.account_id = current_account.id
            @post.community_id = params[:community_id]
            if @post.save
                redirect_to community_path(@post.community_id)
            else
                @community = Community.find(params[:community_id])
                render :new
            end
    
        end
    
        private
        def set_post
            @post = Post.includes(:comments).find(params[:id])
    
        end
        def auth_subscriber

            unless Subscription.where(community_id: params[:community_id], account_id: current_account.id).any? 
        
            redirect_to root_path, flash: { danger: "you are not authorized to view this page" }
        end

        end
  
    
        def post_values
            params.require(:post).permit(:title, :body)
        end
    
end

app/controllers/public_controller.rb
class PublicController < ApplicationController

    def index
        @communities = Community.all.limit(10)
        @posts = Post.order(created_at: :desc).limit(20)
    end

    def profile
        @profile = Account.find_by_username params[:username]
        @posts = @profile.posts
      
    end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
    def index
    end
    def create
        @subscription = Subscription.new(subscription_params)
        @subscription.account_id = current_account.id
        @subscription.save
        redirect_to community_path(@subscription.community_id) 
    end

    def subscription_params
        params.require(:subscription).permit(:community_id)
    end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
    skip_before_action :verify_authenticity_token  
    def create
       
       post_id  =params[:post_id]
        vote = Vote.new 
        vote.post_id = params[:post_id]
        vote.upvote =params[:upvote]
        vote.account_id = current_account.id

        existing_vote = Vote.where(account_id: current_account.id, post_id: post_id)
       @new_vote = existing_vote.size < 1
        
        respond_to do |format|
         
            format.js {

                if existing_vote.size>0
                    existing_vote.first.destroy
                else
                   
                  
                    if vote.save
                      
                        @success = true
                    else
                        @success = false
                    end
                
                end
                @post = Post.find(post_id)
                @is_upvote = params[:upvote]
                render"votes/create"
         
            }
        end

    end

    private
    def vote_params
        params.require(:vote).permit(:upvote, :post_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/votes_helper.rb
module VotesHelper
    def is_upvoted post
       
            account_signed_in? && current_account.upvoted_post_ids.include?(post.id) ? "active" : ""
       
    end
    def is_downvoted post
       
            account_signed_in? && current_account.downvoted_post_ids.include?(post.id) ? "active" : ""
        
    end
end

app/views/comments/create.js.erb
console.log("Comment created...");
$('#post-comments').html("<%= escape_javascript(render partial: 'posts/comments', locals: {comments: @comments}) %>");

app/views/communities/_form.html.erb
<div class="row">
    <div class="col-sm-6">
    <%= form_for @community do |form| %>
        <div class="form-group">
            <%= label_tag :name %>
            <%= form.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
            <%= label_tag :url  %>
            <%= form.text_field :url, class: "form-control" %>
        </div>
        <div class="form-group">
            <%= label_tag :summary %>
            <%= form.text_area :summary , class: "form-control" %>
        </div>
        <div class="form-group">
        <%= label_tag :Rules %>
        <%= form.text_field :rules , class: "form-control" %>
    </div>
        <%= form.submit "Submit", class: "btn btn-primary" %>
         
    <% end %>
    </div>
</div>

app/views/communities/_subscribe.html.erb
<%= form_for @Subscription do |f| %>
    <%= f.hidden_field :community_id, value: community_id %>
    <%= f.submit "Join Community", class: "btn btn-success text-uppercase float-right" %>
<% end %>

app/views/communities/index.html.erb
<% if account_signed_in? %>
    <div class = "row">
    <div class= "float-right mb-3">
        <%= link_to "Create New Community", new_community_path, class: "btn btn-primary float-right" %>
    </div>
    </div>
<% end %>
   
<% if @communities.size > 0 %>
<% @communities.each do |community| %>
    <div class = "card">
        <h3> <%= link_to community.name, community %></h3>
        <%= simple_format community.rules %>
    </div>
<% end %>

<% else %>
<p>No Comminities to display</p>
<% end %>

app/views/communities/new.html.erb
<h2>New Community </h2>

<%= render partial: "form" %>

app/views/communities/show.html.erb
<div class="row pb-4">
<div class="col-sm-8">
<h3>
<%= @community.name %>
</h3>
</div>
<div class="col-sm-4">
<% if @is_subscribed %>
    <%= link_to "Create new post", new_community_post_path(@community), class: "btn btn-primary float-right"%>
<% else %>
<%= render partial: "communities/subscribe", locals: {community_id: @community.id } %>
<% end %>

</div>
</div>

<div class="row">
<div class="col-sm-8">
<%= render partial: "posts/list", locals: {posts: @posts}%>
</div>
<div class="col-sm-4">
<div class = "card p-3">
<p class="h5"> About this community </h5>
    <p class="mt-3"><%= @community.summary %></p>


<p><%= pluralize @subscriber_count, "member" %></p>
<small>
</div>
<%= simple_format @community.rules %>
</small>
</div>
</div>

app/views/layouts/_header.html.erb
<div class="container">
    <div class = "row">
        <div class="col-12 pt-3 border-bottom ">
            <div class="float-right">
                <% if account_signed_in? %>
                <div class="dropdown show">
                    <a class="btn btn-white dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <%= current_account.full_name %>
                    </a>

                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                      
                        <%= link_to "Profile", profile_path(current_account.username), class: "dropdown-item" %>
                        <%= link_to "Settings", edit_account_registration_path, class: "dropdown-item" %>
                        <%= link_to "Sign Out", destroy_account_session_path, class: "dropdown-item" %>
                    </div>
                </div>

                <% else %>
                    <%= link_to "Log In", new_account_session_path, class: "btn btn-outline-primary" %>
                    <%= link_to "Sign Up", new_account_registration_path, class: "btn btn-primary" %>
                <% end %>
            
            </div>
            <p class="h3"><%= link_to "Reddit Clone", root_path %></p>
            
        </div>

    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reddit Clone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
   
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    </head>

  <body>
    <%= render partial: "layouts/header" %>
    <section class="bg-light">
        <div class = "container">
        <div class = "row">
          <div class = "col-sm-12 pt-4">
            <%= yield %>
          </div>
        </div> 
      </div>
    </section>
   
    


    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    
  </body>
</html>

app/views/posts/_comments.html.erb
<% comments.each do |comment| %> 
    <div class="comment">

        <%= link_to comment.account.full_name, profile_path(comment.account.username) %>
        <%= simple_format comment.message %>

    </div>
<% end %>

app/views/posts/_form.html.erb
<div class="row">
    <div class="col-sm-6">
    <%= form_for [@community, @post] do |form| %>

        <div class="form-group">
            <%= label_tag :title %>
            <%= form.text_field :title, class: "form-control" %>
        </div>
        <div class="form-group">
            <%= label_tag :body  %>
            <%= form.text_field :body, class: "form-control" %>
        </div>
    
        <%= form.submit "Submit", class: "btn btn-primary" %>
         
    <% end %>
    </div>
</div>

app/views/posts/_list.html.erb
<% @posts.each do |post| %>
    <div class="card p-3 mb-3">
        <div class="row">
            <div class="col-1">
            <div id="vote-actions-<%= post.id %>" class="vote" data-id="<%= post.id %>">
                <div class="fa fa-arrow-up upvote <%= is_upvoted post %>"></div>
                <span class="font-weight-bold score"><%= post.score %></span>
                <div class="fa fa-arrow-down downvote <%= is_downvoted post %>"></div>

            </div>

            </div>

            <div class="col-11">
                <h4 class="mb-0"><%= link_to post.title, community_post_path(post.community_id, post) %></h4>
                <p><small><%= link_to post.community.name, community_path(post.community_id) %> Posted by <%= link_to post.account.full_name, profile_path(post.account.username) %> <%= time_ago_in_words post.created_at %> ago.</small></p>
            
                    <p>
                    <%= truncate post.body, length: 200 %> 
                    </p>
            </div>
            
        </div>
    </div>
  
<% end %>

<script>
$(function(){
    $(".vote").on("click",".upvote, .downvote", function(){
        
        var post_id = $(this).parent().data("id");
        var is_upvote = $(this).hasClass("upvote");
        console.log("upvote for post" +post_id);
        console.log("is an upvote" +is_upvote);

        $.ajax({
            url: "/post/vote",
            method: "POST",
            data: {post_id: post_id, upvote: is_upvote},
            success: function(){
                console.log("success..")
            }
        })

  

    });
});
</script>

app/views/posts/edit.html.erb
<h2>Edit Post</h2>

<%= render partial: "form" %>

app/views/posts/new.html.erb
<h2>New Post </h2>

<%= render partial: "form" %>

app/views/posts/show.html.erb
<div class="card p-3">
<div class = "row">
<div class = "col-1">
    <div id="vote-actions-<%= @post.id %>" class="vote" data-id="<%= @post.id %>">
    <div class="fa fa-arrow-up upvote <%= is_upvoted @post %>"></div>
    <span class="font-weight-bold score"><%= @post.score %></span>
    <div class="fa fa-arrow-down downvote <%= is_downvoted @post %>"></div>
    </div>


</div>

<div class = "col-11">
<h2><%= @post.title %> </h2>


<%= simple_format @post.body %>

<div id="post-comments">
    <%= render partial: "posts/comments", locals: { comments: @post.comments } %>
</div>
<p class="h5">Leave a comment </p>

<%= form_for @comment, remote: true do |f| %>
    <%= f.hidden_field :post_id, value: @post.id%>
    <%= f.text_area :message, placeholder: "your comment goes here", class: "form-control" %>
    <%= f.submit "Submit comment", class: "btn btn-success mt-3" %>
<% end %>

</div>
</div>
</div>

app/views/votes/create.js.erb
$("#vote-actions-<%= @post.id %> .score").text("<%= @post.score %>");
$("#vote-actions-<%= @post.id %> .downvote, #vote-actions-<%= @post.id %> .upvote").removeClass("active");

<% if @new_vote %>
<%if @is_upvote == "true" %>
  
    $("#vote-actions-<%= @post.id %> .upvote").addClass("active");
    <% else %>
      $("#vote-actions-<%= @post.id %> .downvote").addClass("active");

<% end %>
<% end %>